// locationData.ts
export const stateOptions = [
  "Delhi",
  "Maharashtra",
  "Karnataka",
  "Tamil Nadu",
  "Uttar Pradesh",
  "West Bengal",
  "Gujarat",
  "Rajasthan",
  "Punjab",
  "Kerala",
  "Bihar",
  "Madhya Pradesh",
  "Andhra Pradesh",
  "Telangana",
  "Odisha",
  "Chhattisgarh",
  "Assam",
  "Jharkhand",
  "Haryana",
  "Uttarakhand",
  "Himachal Pradesh",
  "Goa",
  "Tripura",
  "Meghalaya",
  "Manipur",
  "Nagaland",
  "Arunachal Pradesh",
  "Sikkim",
  "Mizoram",
];

export const countryOptions = ["India"];

export const citiesByState: Record<string, string[]> = {
  Delhi: ["New Delhi", "Dwarka", "Rohini", "Saket"],
  Maharashtra: ["Mumbai", "Pune", "Nagpur", "Nashik"],
  Karnataka: ["Bengaluru", "Mysuru", "Mangalore"],
  "Tamil Nadu": ["Chennai", "Coimbatore", "Madurai"],
  "Uttar Pradesh": ["Lucknow", "Kanpur", "Noida", "Agra"],
  "West Bengal": ["Kolkata", "Howrah", "Durgapur"],
  Gujarat: ["Ahmedabad", "Surat", "Vadodara"],
  Rajasthan: ["Jaipur", "Udaipur", "Jodhpur"],
  Punjab: ["Amritsar", "Ludhiana", "Jalandhar"],
  Kerala: ["Kochi", "Thiruvananthapuram", "Kozhikode"],
  Bihar: ["Patna", "Gaya", "Muzaffarpur"],
  "Madhya Pradesh": ["Bhopal", "Indore", "Jabalpur"],
  "Andhra Pradesh": ["Visakhapatnam", "Vijayawada", "Guntur"],
  Telangana: ["Hyderabad", "Warangal", "Nizamabad"],
  Odisha: ["Bhubaneswar", "Cuttack", "Rourkela"],
  Chhattisgarh: ["Raipur", "Bilaspur", "Durg"],
  Assam: ["Guwahati", "Silchar", "Dibrugarh"],
  Jharkhand: ["Ranchi", "Jamshedpur", "Dhanbad"],
  Haryana: ["Gurgaon", "Faridabad", "Panipat"],
  Uttarakhand: ["Dehradun", "Haridwar", "Nainital"],
  "Himachal Pradesh": ["Shimla", "Manali", "Dharamshala"],
  Goa: ["Panaji", "Margao", "Vasco da Gama"],
  Tripura: ["Agartala"],
  Meghalaya: ["Shillong"],
  Manipur: ["Imphal"],
  Nagaland: ["Kohima"],
  "Arunachal Pradesh": ["Itanagar"],
  Sikkim: ["Gangtok"],
  Mizoram: ["Aizawl"],
};
